# Installation de la librairie Sckit Learn

In [11]:
# install Scikit Learn Library
!pip install sklearn 

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1316 sha256=19772d3cc4830d0b668d8db420612f11a008aa1fad4ef5759770ada6c9f4ec5e
  Stored in directory: c:\users\lamin\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn


# Importation des différents packages

In [139]:
import numpy as np
import pandas as pd
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn import svm
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures, StandardScaler, LabelBinarizer
from sklearn.model_selection import learning_curve, train_test_split, GridSearchCV
from sklearn.metrics import f1_score, classification_report, confusion_matrix, accuracy_score
from sklearn.pipeline import make_pipeline
import seaborn as sb
import seaborn as sns

# Importation des données train et test

In [7]:
data_train=pd.read_csv("Machine learning et Insuffisance Cardiaque_train.csv")
data_train

In [5]:
data_test=pd.read_csv("Machine learning et Insuffisance Cardiaque_test.csv")
data_test=data_tes.set_index("trustii_id")
data_test

age  anaemia  creatinine_phosphokinase  diabetes  \
trustii_id                                                      
1           58.0      0.0                     144.0       1.0   
2           50.0      1.0                     249.0       1.0   
3           60.0      0.0                     166.0       0.0   
4           60.0      0.0                     235.0       1.0   
5           86.0      0.0                     582.0       0.0   
...          ...      ...                       ...       ...   
86          85.0      0.0                    5882.0       0.0   
87          55.0      0.0                     572.0       1.0   
88          50.0      1.0                     582.0       1.0   
89          60.0      0.0                    2261.0       0.0   
90          60.0      0.0                     582.0       1.0   

            ejection_fraction  high_blood_pressure  platelets  \
trustii_id                                                      
1                        38.0                  1.0  327000.00   
2                        35.0                  1.0  319000.00   
3                        30.0                  0.0   62000.00   
4                        38.0                  0.0  329000.00   
5                        38.0                  0.0  263358.03   
...                       ...                  ...        ...   
86                       35.0                  0.0  243000.00   
87                       35.0                  0.0  231000.00   
88                       20.0                  1.0  279000.00   
89                       35.0                  1.0  228000.00   
90                       38.0                  1.0  451000.00   

            serum_creatinine  serum_sodium  sex  smoking   time  
trustii_id                                                       
1                       0.70         142.0  0.0      0.0   83.0  
2                       1.00         128.0  0.0      0.0   28.0  
3                       1.70         127.0  0.0      0.0  207.0  
4                       3.00         142.0  0.0      0.0   30.0  
5                       1.83         134.0  0.0      0.0   95.0  
...                      ...           ...  ...      ...    ...  
86                      1.00         132.0  1.0      1.0   72.0  
87                      0.80         143.0  0.0      0.0  215.0  
88                      1.00         134.0  0.0      0.0  186.0  
89                      0.90         136.0  1.0      0.0  115.0  
90                      0.60         138.0  1.0      1.0   40.0  

[90 rows x 12 columns]

# Définition de la variable explicative et de la variable cible

In [10]:
x_train = data_train.drop(columns=['DEATH_EVENT'])
x_train

age  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    73.0                     582.0       0.0               20.0   
1    70.0                     212.0       1.0               17.0   
2    60.0                     737.0       0.0               60.0   
3    45.0                     615.0       1.0               55.0   
4    55.0                     748.0       0.0               45.0   
..    ...                       ...       ...                ...   
204  44.0                      84.0       1.0               40.0   
205  46.0                     719.0       0.0               40.0   
206  60.0                      68.0       0.0               20.0   
207  53.0                      91.0       0.0               20.0   
208  46.0                     168.0       1.0               17.0   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    0.0  263358.03              1.83         134.0  1.0   
1                    1.0  389000.00              1.00         136.0  1.0   
2                    1.0  210000.00              1.50         135.0  1.0   
3                    0.0  222000.00              0.80         141.0  0.0   
4                    0.0  263000.00              1.30         137.0  1.0   
..                   ...        ...               ...           ...  ...   
204                  1.0  235000.00              0.70         139.0  1.0   
205                  1.0  263358.03              1.18         137.0  0.0   
206                  0.0  119000.00              2.90         127.0  1.0   
207                  1.0  418000.00              1.40         139.0  0.0   
208                  1.0  271000.00              2.10         124.0  0.0   

     smoking   time  
0        0.0  198.0  
1        1.0  188.0  
2        1.0   95.0  
3        0.0  257.0  
4        0.0   88.0  
..       ...    ...  
204      0.0   79.0  
205      0.0  107.0  
206      1.0   64.0  
207      0.0   43.0  
208      0.0  100.0  

[209 rows x 11 columns]

In [12]:
#define the target column
y_train=data_train['DEATH_EVENT']
y_train

0      1
1      0
2      0
3      0
4      0
      ..
204    0
205    0
206    1
207    1
208    1
Name: DEATH_EVENT, Length: 209, dtype: int64

# Vérifier comment chaque colonne est corrélée avec la variable cible

In [143]:
cor=data_train.corr()['DEATH_EVENT'].sort_values()
cor

time                       -0.514821
ejection_fraction          -0.323594
serum_sodium               -0.191731
smoking                    -0.026725
sex                        -0.019820
diabetes                   -0.004372
platelets                  -0.002858
anaemia                     0.052410
creatinine_phosphokinase    0.079700
high_blood_pressure         0.156014
age                         0.275377
serum_creatinine            0.311184
DEATH_EVENT                 1.000000
Name: DEATH_EVENT, dtype: float64

In [144]:
#Checking and highliting the variables which has high correletion
DF=data_train.corr()
def highlight(s):
    return ['background-color: yellow' if (v>0.4) or (v<-0.9) else 'background-color: white' for v in s]
DF.style.apply(highlight, axis=0)

# On voit que il est possible de supprimer la variable 'anaemie' car elle peut être expliquée par les autres

In [ ]:
x_train = x_train.drop(columns=['anaemia'])
x_train

In [75]:
#data_test=data_test.drop(columns='high_blood_pressure')
data_test = data_test.drop(columns=['anaemia'])
data_test

age  creatinine_phosphokinase  diabetes  ejection_fraction  \
trustii_id                                                                
1           58.0                     144.0       1.0               38.0   
2           50.0                     249.0       1.0               35.0   
3           60.0                     166.0       0.0               30.0   
4           60.0                     235.0       1.0               38.0   
5           86.0                     582.0       0.0               38.0   
6           66.0                      68.0       1.0               38.0   
7           43.0                     358.0       0.0               50.0   
8           51.0                     582.0       1.0               40.0   
9           90.0                      47.0       0.0               40.0   
10          53.0                      56.0       0.0               50.0   
11          55.0                    1199.0       0.0               20.0   
12          80.0                     776.0       1.0               38.0   
13          45.0                     981.0       0.0               30.0   
14          73.0                     582.0       0.0               35.0   
15          63.0                     103.0       1.0               35.0   
16          70.0                      75.0       0.0               35.0   
17          65.0                     258.0       1.0               25.0   
18          44.0                     582.0       1.0               30.0   
19          70.0                     835.0       0.0               35.0   
20          60.0                     588.0       1.0               60.0   
21          53.0                    1808.0       0.0               60.0   
22          60.0                     156.0       1.0               25.0   
23          62.0                     281.0       1.0               35.0   
24          85.0                     129.0       0.0               60.0   
25          90.0                     337.0       0.0               38.0   
26          59.0                     176.0       1.0               25.0   
27          55.0                     109.0       0.0               35.0   
28          45.0                    2413.0       0.0               38.0   
29          70.0                      66.0       1.0               45.0   
30          60.0                      47.0       0.0               20.0   
31          65.0                     198.0       1.0               35.0   
32          65.0                     118.0       0.0               50.0   
33          55.0                     582.0       1.0               35.0   
34          70.0                      81.0       1.0               35.0   
35          48.0                     582.0       1.0               55.0   
36          55.0                     180.0       0.0               45.0   
37          85.0                     102.0       0.0               60.0   
38          70.0                      97.0       0.0               60.0   
39          80.0                     148.0       1.0               38.0   
40          45.0                     582.0       1.0               55.0   
41          53.0                     207.0       1.0               40.0   
42          65.0                     305.0       0.0               25.0   
43          70.0                     161.0       0.0               25.0   
44          70.0                    1202.0       0.0               50.0   
45          50.0                    1051.0       1.0               30.0   
46          70.0                     571.0       1.0               45.0   
47          52.0                      58.0       0.0               35.0   
48          45.0                    2442.0       1.0               30.0   
49          64.0                     143.0       0.0               25.0   
50          50.0                     245.0       0.0               45.0   
51          70.0                     125.0       0.0               25.0   
52          51.0                     5

# Les différents modèles à tester

In [146]:
RandomForest = RandomForestClassifier()
GradientBoosting = GradientBoostingClassifier()
AdaBoost = AdaBoostClassifier()
DecisionTree = DecisionTreeClassifier()
KNN = KNeighborsClassifier()
SVM = SVC()
Logistic = LogisticRegression(solver='liblinear')
SGD = SGDClassifier()

# Evaluation des modéles

In [150]:
def evaluation(model):
    model.fit(x_train, y_train)
    y_pred=model.predict(x_train)
    print(confusion_matrix(y_pred,y_train))
    print(classification_report(y_pred,y_train))
    print(accuracy_score(y_train,y_pred))

In [155]:
dict_of_models={'RandomForest':RandomForest, 'GradientBoosting':GradientBoosting, 'AdaBoost':AdaBoost,
                'DecisionTree':DecisionTree,'KNN':KNN, 'SVM':SVM, 'Logistic':Logistic, 'SGD':SGD}

In [156]:
for name, model in dict_of_models.items():
    print(name)
    evaluation(model)

RandomForest
[[142   0]
 [  0  67]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       142
           1       1.00      1.00      1.00        67

    accuracy                           1.00       209
   macro avg       1.00      1.00      1.00       209
weighted avg       1.00      1.00      1.00       209

1.0
GradientBoosting
[[142   0]
 [  0  67]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       142
           1       1.00      1.00      1.00        67

    accuracy                           1.00       209
   macro avg       1.00      1.00      1.00       209
weighted avg       1.00      1.00      1.00       209

1.0
AdaBoost
[[139   4]
 [  3  63]]
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       143
           1       0.94      0.95      0.95        66

    accuracy                           0.97       209
   macro avg

C:\Users\lamin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\lamin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\lamin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\lamin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1

# On voit que les modèles: RandomForest, GradientBoosting, AdaBoost et DecisionTree nous donnent de meilleurs score par rapport aux autres modèles

# On va commencer par le modèle RandomForestClassifier pour l'entrainer et l'utiliser sur data_test

In [184]:
modele=RandomForestClassifier()
modele.fit(x_train,y_train)
prd=modele.predict(x_train)
print("Test confusion matrix :\n",confusion_matrix(prd, y_train))
print("Test Accuracy :",accuracy_score(prd, y_train))

Test confusion matrix :
 [[142   0]
 [  0  67]]
Test Accuracy : 1.0


# Prédiction sur le train et test data

In [185]:
p1=modele.predict(x_train)
p1

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [186]:
p=modele.predict(data_test)
p

0     0
1     1
2     0
3     1
4     1
5     0
6     0
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    0
15    1
16    0
17    0
18    0
19    1
20    0
21    1
22    0
23    0
24    0
25    0
26    1
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    1
35    0
36    1
37    0
38    1
39    0
40    0
41    0
42    1
43    0
44    0
45    1
46    0
47    0
48    0
49    0
50    1
51    0
52    0
53    0
54    0
55    0
56    0
57    0
58    0
59    0
60    0
61    1
62    0
63    0
64    1
65    0
66    0
67    0
68    1
69    0
70    0
71    0
72    0
73    0
74    0
75    1
76    0
77    1
78    0
79    0
80    0
81    1
82    0
83    0
84    0
85    0
86    0
87    0
88    0
89    1
Name: DEATH_EVENT, dtype: int64

# Ajout de la colonne cible prédite dans le data_test

In [187]:
data_test["DEATH_EVENT"]=p
data_test

age  creatinine_phosphokinase  diabetes  ejection_fraction  \
trustii_id                                                                
1           58.0                     144.0       1.0               38.0   
2           50.0                     249.0       1.0               35.0   
3           60.0                     166.0       0.0               30.0   
4           60.0                     235.0       1.0               38.0   
5           86.0                     582.0       0.0               38.0   
6           66.0                      68.0       1.0               38.0   
7           43.0                     358.0       0.0               50.0   
8           51.0                     582.0       1.0               40.0   
9           90.0                      47.0       0.0               40.0   
10          53.0                      56.0       0.0               50.0   
11          55.0                    1199.0       0.0               20.0   
12          80.0                     776.0       1.0               38.0   
13          45.0                     981.0       0.0               30.0   
14          73.0                     582.0       0.0               35.0   
15          63.0                     103.0       1.0               35.0   
16          70.0                      75.0       0.0               35.0   
17          65.0                     258.0       1.0               25.0   
18          44.0                     582.0       1.0               30.0   
19          70.0                     835.0       0.0               35.0   
20          60.0                     588.0       1.0               60.0   
21          53.0                    1808.0       0.0               60.0   
22          60.0                     156.0       1.0               25.0   
23          62.0                     281.0       1.0               35.0   
24          85.0                     129.0       0.0               60.0   
25          90.0                     337.0       0.0               38.0   
26          59.0                     176.0       1.0               25.0   
27          55.0                     109.0       0.0               35.0   
28          45.0                    2413.0       0.0               38.0   
29          70.0                      66.0       1.0               45.0   
30          60.0                      47.0       0.0               20.0   
31          65.0                     198.0       1.0               35.0   
32          65.0                     118.0       0.0               50.0   
33          55.0                     582.0       1.0               35.0   
34          70.0                      81.0       1.0               35.0   
35          48.0                     582.0       1.0               55.0   
36          55.0                     180.0       0.0               45.0   
37          85.0                     102.0       0.0               60.0   
38          70.0                      97.0       0.0               60.0   
39          80.0                     148.0       1.0               38.0   
40          45.0                     582.0       1.0               55.0   
41          53.0                     207.0       1.0               40.0   
42          65.0                     305.0       0.0               25.0   
43          70.0                     161.0       0.0               25.0   
44          70.0                    1202.0       0.0               50.0   
45          50.0                    1051.0       1.0               30.0   
46          70.0                     571.0       1.0               45.0   
47          52.0                      58.0       0.0               35.0   
48          45.0                    2442.0       1.0               30.0   
49          64.0                     143.0       0.0               25.0   
50          50.0                     245.0       0.0               45.0   
51          70.0                     125.0       0.0               25.0   
52          51.0                     5

# Exportation du data_test prédit

In [81]:
data_test.to_csv('validation_cardiaque26.csv',encoding='UTF-8')